version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carrerpro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sys@dmin

  node_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - postgres